source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'examplePod_Example', :exclusive => true do
  pod 'examplePod', :path => '../'
end

target 'examplePod_Tests', :exclusive => true do
  pod 'examplePod', :path => '../'

  
end
